* nppcommands.cpp(2633): error C2440: 'initializing': cannot convert from 'const char [11]' to 'char *' 	old: char *authorName =  ... 	new: const char* authorName= ... 	or: auto authorName= ...